addons:
  postgresql: "9.4"
before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis-ci@example.com"
branches:
  only:
    - master
install:
  - travis_retry bin/setup
language:
  - ruby
notifications:
  email: false
rvm:
  - 2.3
  - 2.2
  - 2.1
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails50.gemfile
